// <auto-generated />
using System;
using Hospital.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315161831_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Hospital.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("personId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("personId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Hospital.Models.DoctorCheckups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("DoctorCheckups");
                });

            modelBuilder.Entity("Hospital.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserRole");

                    b.Property<int>("UserRole")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Persons", t =>
                        {
                            t.Property("UserRole")
                                .HasColumnName("UserRole1");
                        });

                    b.HasDiscriminator<int>("UserRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hospital.Models.Admin", b =>
                {
                    b.HasBaseType("Hospital.Models.Person");

                    b.ToTable("Persons", t =>
                        {
                            t.Property("UserRole")
                                .HasColumnName("UserRole1");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Hospital.Models.Doctor", b =>
                {
                    b.HasBaseType("Hospital.Models.Person");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Persons", t =>
                        {
                            t.Property("UserRole")
                                .HasColumnName("UserRole1");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Hospital.Models.Patient", b =>
                {
                    b.HasBaseType("Hospital.Models.Person");

                    b.ToTable("Persons", t =>
                        {
                            t.Property("UserRole")
                                .HasColumnName("UserRole1");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Hospital.Models.Account", b =>
                {
                    b.HasOne("Hospital.Models.Person", "person")
                        .WithOne("Account")
                        .HasForeignKey("Hospital.Models.Account", "personId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("Hospital.Models.DoctorCheckups", b =>
                {
                    b.HasOne("Hospital.Models.Doctor", "Doctor")
                        .WithMany("DoctorCheckups")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Models.Patient", "Patient")
                        .WithMany("DoctorCheckups")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital.Models.Person", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.Models.Doctor", b =>
                {
                    b.Navigation("DoctorCheckups");
                });

            modelBuilder.Entity("Hospital.Models.Patient", b =>
                {
                    b.Navigation("DoctorCheckups");
                });
#pragma warning restore 612, 618
        }
    }
}
